# NumPy Mathematical Operations

In [1]:
import numpy as np

#### sample dataset

In [2]:
scores = np.array([78, 85, 92, 67, 88, 95, 73, 81])

print(scores)

[78 85 92 67 88 95 73 81]


### 1. Sum

The Sum function calculates the total of all elements in an array.

It is useful when finding the total marks, total sales, total revenue, or total values in a dataset.

In [3]:
total = np.sum(scores)

print(total)

659


### 2. Mean

The Mean is the average value of all numbers.

It is calculated by dividing the sum of all values by the total number of values.

In [4]:
average = np.mean(scores)

print(average)

82.375


### 3. Median

The Median is the middle value after arranging the numbers in ascending order.

If there are two middle values, NumPy returns their average.

In [5]:
median = np.median(scores)

print(median)

83.0


### 4. Variance

Variance measures how far the data points are spread from the mean.

* Small variance → values are close together.
* Large variance → values are widely spread.

In [6]:
variance = np.var(scores)

print(variance)

79.484375


### 5. Standard Deviation

Standard Deviation measures the average distance of data points from the mean.

It is simply the square root of the variance.

In [7]:
std = np.std(scores)

print(std)

8.915401000515905


### 6. Minimum

Returns the smallest value in the array.

In [8]:
minimum = np.min(scores)

print(minimum)

67


### 7. Maximum

Returns the largest value in the array.

In [9]:
maximum = np.max(scores)

print(maximum)

95


### 8. Argmin

Returns the index of the smallest value.

* min() → value
* argmin() → position

In [10]:
print(np.argmin(scores))

3


Because

scores[3] = 67

### 9. Argmax

Returns the index of the largest value.

In [11]:
print(np.argmax(scores))

5


Because

scores[5] = 95

### 10. Percentile

A percentile indicates the value below which a certain percentage of observations fall.

Examples:

* 25th percentile
* 50th percentile (Median)
* 75th percentile

In [13]:
print(np.percentile(scores,25))

print(np.percentile(scores,50))

print(np.percentile(scores,75))

76.75
83.0
89.0


### 11. Dot Product

The dot product multiplies corresponding elements of two vectors and then adds the results.

It is one of the most important operations in Machine Learning.

In [14]:
a = np.array([2,3,4])

b = np.array([5,6,7])

print(np.dot(a,b))

56


Calculation

(2×5)+(3×6)+(4×7)

10+18+28=56

### 12. Matrix Multiplication

Matrix multiplication combines two matrices to produce another matrix.

The number of columns in the first matrix must equal the number of rows in the second matrix.

In [15]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

#### Method 1

In [16]:
print(np.matmul(A,B))

[[19 22]
 [43 50]]


#### Method 2

In [17]:
print(np.matmul(A,B))


[[19 22]
 [43 50]]


### 13. Transpose

Transpose converts rows into columns and columns into rows.

In [18]:
A = np.array([[1,2,3],
              [4,5,6]])

print(A.T)


[[1 4]
 [2 5]
 [3 6]]


### 14. Basic Linear Algebra Operations

Linear Algebra forms the mathematical foundation of Artificial Intelligence and Machine Learning.

#### Addition

In [19]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A+B)

[[ 6  8]
 [10 12]]


#### Subtraction

In [20]:
print(A-B)

[[-4 -4]
 [-4 -4]]


#### Scalar Multiplication

In [21]:
print(A*3)

[[ 3  6]
 [ 9 12]]


#### Matrix Multiplication

In [22]:
print(A@B)

[[19 22]
 [43 50]]


#### Determinant

The determinant is a single value that tells us important properties of a square matrix, such as whether it has an inverse.

In [23]:
print(np.linalg.det(A))

-2.0000000000000004


#### Inverse

The inverse of a matrix is used to solve systems of linear equations.

In [24]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


#### Rank

The rank of a matrix tells the number of linearly independent rows or columns.

In [25]:
print(np.linalg.matrix_rank(A))

2


#### Eigenvalues and Eigenvectors

Eigenvalues and eigenvectors describe the directions in which a matrix stretches or compresses data.

In [26]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues")

print(eigenvalues)

print()

print("Eigenvectors")

print(eigenvectors)

Eigenvalues
[-0.37228132+0.j  5.37228132+0.j]

Eigenvectors
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]
