# Introduction to NumPy

### What is NumPy?
NumPy (Numerical Python) is an open-source Python library used for performing mathematical and numerical operations efficiently. It provides a powerful object called ndarray (N-dimensional array) that stores data in a compact and optimized format.

NumPy is the foundation of many AI and Machine Learning libraries such as:

* Pandas
* Scikit-learn
* TensorFlow
* PyTorch
* OpenCV

In [2]:
import numpy as np

arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


#### AI/ML Usage

Almost every Machine Learning dataset is converted into NumPy arrays before training a model because mathematical calculations are much faster.

### Why NumPy?

Python lists are useful, but they become slow when working with large datasets.

NumPy provides:

* Faster computation
* Less memory usage
* Built-in mathematical functions
* Easy matrix operations
* Supports multidimensional arrays

In [3]:
import numpy as np

python_list = [1,2,3,4]

numpy_array = np.array([1,2,3,4])

print(type(python_list))
print(type(numpy_array))

<class 'list'>
<class 'numpy.ndarray'>


#### AI/ML Usage

Machine learning algorithms perform thousands of mathematical operations.

Using NumPy makes these operations much faster than Python lists.

### NumPy Arrays (ndarray)

The main object in NumPy is called ndarray (N-dimensional array).

It stores data of the same data type in one place.

Unlike Python lists, NumPy arrays are homogeneous.

In [4]:
import numpy as np

arr = np.array([5,10,15,20])
print(arr)

[ 5 10 15 20]


#### AI/ML Usage

Dataset features are usually stored as NumPy arrays before training models.

Example:

* Age
* Salary
* Experience

which becomes,

In [5]:
data = np.array([
    [25,40000,2],
    [30,50000,5],
    [35,60000,8]
])

print(data)

[[   25 40000     2]
 [   30 50000     5]
 [   35 60000     8]]


### Creating Arrays

In [6]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


### Dimensions

Dimension means the number of axes in an array.

* [1,2,3]        ->	1D
* [[1,2],[3,4]]	 -> 2D
* [[[1]]]        ->	3D

In [7]:
import numpy as np

a = np.array([1,2,3])

b = np.array([[1,2],[3,4]])

c = np.array([[[1],[2]],[[3],[4]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


#### AI/ML Usage

* Images → 3D arrays
* Videos → 4D arrays
* Deep Learning batches → 4D or 5D arrays

### Shape

Shape tells how many rows and columns exist.

In [8]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.shape)

(2, 3)


Meaning

* 2 rows
* 3 columns

#### AI/ML Usage

Before training a model, checking the dataset shape ensures the data is in the correct format.

### Size

Size means the total number of elements.

In [9]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.size)

6


### Data Types

NumPy stores one data type per array.

Common types:

* int32
* int64
* float32
* float64
* bool
* str

In [10]:
arr = np.array([10,20,30])

print(arr.dtype)

int64


#### Changing datatype


In [11]:
arr = arr.astype(float)

print(arr)
print(arr.dtype)

[10. 20. 30.]
float64


#### AI/ML Usage

Deep learning often uses float32 because it consumes less memory and trains faster.


### Indexing

Indexing accesses individual elements.

In [12]:
arr = np.array([10,20,30,40])

print(arr[0])
print(arr[2])

10
30


#### 2D

In [13]:
arr = np.array([[1,2],[3,4]])

print(arr[1,0])

3


#### AI/ML Usage

Selecting a specific feature column.

### Slicing

Extract multiple values.

In [14]:
arr = np.array([10,20,30,40,50])

print(arr[1:4])

[20 30 40]


#### 2D Slicing

In [16]:
arr = np.array([10,20,30,40,50])

print(arr[1:4])

[20 30 40]


#### AI/ML Usage

* Selecting input features.
* Selecting target column.

### Reshaping

Changes the shape without changing the data.


In [18]:
arr = np.arange(12)

new = arr.reshape(3,4)
print(new)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### AI/ML Usage

Images are reshaped before training CNNs.

### Flatten

Converts multidimensional arrays into one dimension.

In [19]:
arr = np.array([[1,2],
                [3,4]])

flat = arr.flatten()
print(flat)

[1 2 3 4]


#### AI/ML Usage

Some machine learning models require flattened image data.

### Copy vs View
#### Copy

Creates a completely separate array.

In [20]:
arr = np.array([1,2,3])

copy = arr.copy()

copy[0]=100

print(arr)
print(copy)

[1 2 3]
[100   2   3]


#### View

Shares the same memory.

In [21]:
arr = np.array([1,2,3])

view = arr.view()

view[0]=100

print(arr)
print(view)

[100   2   3]
[100   2   3]


#### AI/ML Usage

Copies protect original datasets while preprocessing.

Views save memory for large datasets.

### Broadcasting

Broadcasting allows arrays with different shapes to perform arithmetic operations automatically.

In [23]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

vector = np.array([10,20,30])

print(matrix + vector)

[[11 22 33]
 [14 25 36]]


#### AI/ML Usage

Feature scaling

New Value = Original Value - Mean

Mean values are broadcast across every row.

### Array Operations

Basic arithmetic operations.

In [24]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)

print(a-b)

print(a*b)

print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Some other Operations

In [25]:
print(np.sum(a))

print(np.mean(a))

print(np.max(a))

print(np.min(a))


6
2.0
3
1


#### AI/ML Usage

Used while calculating:

* Mean
* Standard deviation
* Euclidean distance
* Loss functions
* Accuracy metrics

### Universal Functions (ufuncs)

Universal functions are built-in NumPy functions that operate element-wise on arrays.

They are fast because they are implemented in optimized C code.

In [27]:
arr = np.array([1,4,9,16])

print(np.sqrt(arr))

[1. 2. 3. 4.]


Other ufuncs

In [28]:
arr = np.array([1,2,3])

print(np.square(arr))

print(np.exp(arr))

print(np.log(arr))

print(np.sin(arr))

print(np.cos(arr))

print(np.abs([-2,-5,6]))

[1 4 9]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[2 5 6]


#### AI/ML Usage

Ufuncs are commonly used for:

* Feature scaling
* Data normalization
* Activation functions
* Statistical calculations
* Distance computations