# NumPy Random Module

In [1]:
import numpy as np

### 1. Random Numbers

Random numbers are numbers generated without following a fixed pattern.

NumPy provides the random module to generate random values quickly.

The generated numbers are usually floating-point numbers between 0 and 1.

#### Example
Imagine you're building an online gaming application where a treasure chest gives a random reward every time a player opens it. The reward should be unpredictable.

In [17]:
reward = np.random.rand()
print(reward)

0.596850157946487


If the number is:

* Less than 0.3 → Bronze Reward
* Between 0.3 and 0.7 → Silver Reward
* Above 0.7 → Gold Reward

#### AI/ML Usage

Random numbers are used to initialize neural network weights and simulate random events during model training.

### 2. Random Seed

A Random Seed fixes the sequence of random numbers.

Without setting a seed, different random numbers are generated every time the program runs.

Using a seed ensures reproducible results, which is very important in Machine Learning experiments.

#### Example
Two data scientists are working on the same customer churn model. They want to get exactly the same train-test split so they can compare their results fairly.

In [16]:
np.random.seed(42)
print(np.random.randint(1,100,5))

[52 93 15 72 61]


Every team member running this code gets the same output.

#### AI/ML Usage

Random seeds make machine learning experiments reproducible.

### 3. Random Integers

Generates random integer values within a specified range.

#### Example
A teacher wants to generate 10 random roll numbers for selecting students to answer questions.

In [15]:
roll_numbers = np.random.randint(1,51,size=10)
print(roll_numbers)

[26  2 20 28 47  7 44  8 47 35]


#### AI/ML Usage

Used for generating sample datasets, customer IDs, labels, and testing algorithms.

### 4. Random Choice

Selects random values from a given list or array.

It can also generate random values according to specified probabilities.

#### Example
An e-commerce company wants to randomly choose one customer for a free gift.

In [14]:
customers = ["Aishu","Rahul","Priya","John","Meena"]

winner = np.random.choice(customers)
print(winner)

Aishu


#### AI/ML Usage

Used in bootstrap sampling, mini-batch selection, and recommendation systems.

### 5. Shuffle

Shuffle randomly rearranges the elements of an array.

It changes the original array.

#### Example
Suppose exam questions are arranged in order. Before giving the paper to students, the questions are shuffled.

In [13]:
questions = np.array([1,2,3,4,5,6])

np.random.shuffle(questions)
print(questions)

[6 3 5 2 4 1]


#### AI/ML Usage

Training datasets are shuffled before every training epoch to prevent the model from learning patterns based on data order.

### 6. Permutation

Permutation also rearranges the elements randomly.

Unlike shuffle(), it does not modify the original array. Instead, it returns a new shuffled array.

#### Example
A company has employee IDs stored in a list. The HR team wants a random order for assigning interview slots but doesn't want to change the original list.

In [12]:
employees = np.array([101,102,103,104,105])

random_order = np.random.permutation(employees)

print("Original:",employees)
print("Interview Order:",random_order)

Original: [101 102 103 104 105]
Interview Order: [105 104 102 103 101]


#### AI/ML Usage

Used for train-test splitting and randomized experiments while preserving the original dataset.

### 7. Random Distributions

A Random Distribution generates numbers that follow a specific statistical pattern instead of being completely random.

Some commonly used distributions are:

* Uniform Distribution
* Normal Distribution
* Binomial Distribution

These are widely used in AI, ML, simulations, and statistical modeling.

### A. Uniform Distribution

Every value has an equal chance of being selected.

#### Example
Suppose an online shopping website wants to generate a random discount between 10% and 20%, where every value has an equal chance.

In [11]:
discount = np.random.uniform(10,20,5)
print(discount)

[13.82461991 19.83230886 14.66762893 18.59940407 16.80307539]


#### AI/ML Usage

Used in random simulations and weight initialization.

### B. Normal Distribution

Generates values that follow a bell-shaped curve.

Most values are close to the mean.

#### Example
The heights of students in a school usually follow a normal distribution.

In [18]:
import numpy as np

heights = np.random.normal(
    loc=165,
    scale=7,
    size=10
)

print(heights)

[158.58221209 164.13096974 150.92325977 161.55037603 167.74805825
 158.49570733 165.55882269 163.88338449 165.15555279 162.0054496 ]


Most students are close to 165 cm, while very short and very tall students are less common.

#### AI/ML Usage

Used for generating realistic datasets, adding noise, and initializing neural network parameters.

### C. Binomial Distribution

Produces the number of successes in a fixed number of independent trials.

#### Example
A cricket player plays 10 balls. Each ball has a 60% chance of scoring a run. We want to know how many successful scoring shots occur.

In [19]:
import numpy as np

runs = np.random.binomial(
    n=10,
    p=0.6,
    size=5
)

print(runs)

[6 8 3 7 8]


Each value represents the number of successful scoring shots out of 10 balls.

#### AI/ML Usage

Used in binary classification, success/failure experiments, A/B testing, and probability modeling.